project:
  type: manuscript

code-links:
  - repo
  - binder

execute:
  freeze: auto

format:
  html:
    # embed-resources: false
    # notebook-links: false
    toc: true
    comments:
      hypothesis: true
  docx:
    reference-doc: custom-reference.docx
    line-numbers: false
  jats: default
  nature-pdf:
    journal: 
      cite-style: sn-jnl
    cite-method: natbib
    keep-tex: true

filters:
  - parse-latex

