project:
  type: manuscript
  render: 
    - "index.qmd"
    - "!pyvenv_csvo/"

execute:
  freeze: auto

format:
  html:
    embed-resources: true
    toc: true
    comments:
      hypothesis: true
      
  docx: default
  jats: default
  
  nature-pdf:
    journal: "sn-nature"
    keep-tex: true

filters:
  - parse-latex

