project:
  type: manuscript
  # render: 
  #   - "*.qmd"
  #   - "!pyvenv_csvo/"
  #   - "*.ipynb"

code-links:
  - repo
  - binder

execute:
  freeze: auto

format:
  html:
    # embed-resources: true
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  nature-pdf:
    journal: "sn-nature"
    keep-tex: true

filters:
  - parse-latex

