project:
  type: manuscript
  # render: 
  #   - "*.qmd"
  #   - "!pyvenv_csvo/"
  #   - "*.ipynb"

# code-links:
#   - repo
#   - binder
notebook-links: false

execute:
  freeze: auto
  cache: false

format:
  # html:
  #   # embed-resources: true
  #   toc: true
  #   comments:
  #     hypothesis: true
  # docx: default
  docx:
    reference-doc: custom-reference.docx
  # jats: default
  nature-pdf:
    journal: 
      cite-style: sn-jnl
    cite-method: natbib
    keep-tex: true

filters:
  - parse-latex

